# 用于安装本工程的仓库代理配置，本文件必须与package.json在同一个路径内
registries:
  "https://registry.npmjs.org": { }

# 代理服务器https配置 可空
#https:
#  key: ~/.ssl/key.pem
#  cert: ~/.ssl/cert.pem

# 代理服务器basePath字符串 可空
#basePath: "npm-proxy"